// import Chance from 'chance';
//
// const chance = new Chance();
//
// const result = new Array(2).fill(1).map(() => chance.sentence());
//
// export default result;

export default [ 'Wobibup jotsubha gucfaus ottermo ovimoh hairazig asibaftus pewoh tegabbe la goheebu tegon.',
  'Lol sih oseeh cabo bam uk ginfor bino saw heube jadu jawetfa vonulu lodtoop je or.',
  'Duawuvo adaiki ufuroje cam kitruwza bevu hulbedus cuskib emev pukja powate il.',
  'Mudemo cego poh tiuc puvle galuno avic war vustione ne od fun fanwon su vomipra gob wucaggak zapavpuf.',
  'Pebgiuko keope awwi jatas ec ete hemaf mocnuvjam wowmurak mocoz rot tu lutzeb bag.',
  'Im fecuusa nu wac pealifad jephummi ca edcek nesilpi ekeati du iwivak doesreb efagev iju.',
  'Ne umube maf we nacenuw gahi sil ki on ewvak vu puc bi awim kal kihrocse fa.',
  'Ucilopet zaluda oheide rohziruz luupu betniz nulji ipanu seved abvebwa geofi ene.',
  'Damsufal ja enu kuwor zez no lop moduzifuj mamem ivicuw si neecuze.',
  'Cafcarji pubhepipu paahwu hanep te jas feg iz rus uvunozeh so jaibela ta tit nun ofulonkes.',
  'Atzah dajivzo sedzoki tu zegov pazip hisbimjo le jerube wawjutti ethun ihzutsa posena.',
  'Po nojajugi kukevim semrok ecdi zu hoc jaddo za rir camomeba ventuane moni cecgajze ovuab.',
  'Ofa ok ezikoke kumesune meagve ape leg biavozi ukebobcuw ij ke waze himidhor rut zuj zew.',
  'Re ik nugvos laize ukahupli kavpur usge jovcu anzer sodol hawi wab.',
  'Imo ulpifum gecignow ifo espa oz dofecgaf ma fophuoha haros toccozip lawi usafe.',
  'Vulorig somgewbem mu uwhiw dehac jiwdifu daoc izoav pevdulhe jaoje roiggif kip.',
  'Pi ebupi tet mukum gublalufu fuice gut vesmuop icut dalocnij ov fumofis vuh nelcos lefe tate sefroka.',
  'Ti anvub zovitogo zi igusapok ju cid wapahih zuwiidi behazah vuz sahbedciz vubru arofe.',
  'Li cejinuki jobo efu asodulruk jevumwo hascu oke durbokwo de loivione laniwu fof neto likuvin.',
  'Kelamci opupaber cilgot faru kediz tef multapu tuepape bez bugse pachirlos ja.',
  'Wobibup jotsubha gucfaus ottermo ovimoh hairazig asibaftus pewoh tegabbe la goheebu tegon.',
  'Lol sih oseeh cabo bam uk ginfor bino saw heube jadu jawetfa vonulu lodtoop je or.',
  'Duawuvo adaiki ufuroje cam kitruwza bevu hulbedus cuskib emev pukja powate il.',
  'Mudemo cego poh tiuc puvle galuno avic war vustione ne od fun fanwon su vomipra gob wucaggak zapavpuf.',
  'Pebgiuko keope awwi jatas ec ete hemaf mocnuvjam wowmurak mocoz rot tu lutzeb bag.',
  'Im fecuusa nu wac pealifad jephummi ca edcek nesilpi ekeati du iwivak doesreb efagev iju.',
  'Ne umube maf we nacenuw gahi sil ki on ewvak vu puc bi awim kal kihrocse fa.',
  'Ucilopet zaluda oheide rohziruz luupu betniz nulji ipanu seved abvebwa geofi ene.',
  'Damsufal ja enu kuwor zez no lop moduzifuj mamem ivicuw si neecuze.',
  'Cafcarji pubhepipu paahwu hanep te jas feg iz rus uvunozeh so jaibela ta tit nun ofulonkes.',
  'Atzah dajivzo sedzoki tu zegov pazip hisbimjo le jerube wawjutti ethun ihzutsa posena.',
  'Po nojajugi kukevim semrok ecdi zu hoc jaddo za rir camomeba ventuane moni cecgajze ovuab.',
  'Ofa ok ezikoke kumesune meagve ape leg biavozi ukebobcuw ij ke waze himidhor rut zuj zew.',
  'Re ik nugvos laize ukahupli kavpur usge jovcu anzer sodol hawi wab.',
  'Imo ulpifum gecignow ifo espa oz dofecgaf ma fophuoha haros toccozip lawi usafe.',
  'Vulorig somgewbem mu uwhiw dehac jiwdifu daoc izoav pevdulhe jaoje roiggif kip.',
  'Pi ebupi tet mukum gublalufu fuice gut vesmuop icut dalocnij ov fumofis vuh nelcos lefe tate sefroka.',
  'Ti anvub zovitogo zi igusapok ju cid wapahih zuwiidi behazah vuz sahbedciz vubru arofe.',
  'Li cejinuki jobo efu asodulruk jevumwo hascu oke durbokwo de loivione laniwu fof neto likuvin.',
  'Kelamci opupaber cilgot faru kediz tef multapu tuepape bez bugse pachirlos ja.',
  'Wobibup jotsubha gucfaus ottermo ovimoh hairazig asibaftus pewoh tegabbe la goheebu tegon.',
  'Lol sih oseeh cabo bam uk ginfor bino saw heube jadu jawetfa vonulu lodtoop je or.',
  'Duawuvo adaiki ufuroje cam kitruwza bevu hulbedus cuskib emev pukja powate il.',
  'Mudemo cego poh tiuc puvle galuno avic war vustione ne od fun fanwon su vomipra gob wucaggak zapavpuf.',
  'Pebgiuko keope awwi jatas ec ete hemaf mocnuvjam wowmurak mocoz rot tu lutzeb bag.',
  'Im fecuusa nu wac pealifad jephummi ca edcek nesilpi ekeati du iwivak doesreb efagev iju.',
  'Ne umube maf we nacenuw gahi sil ki on ewvak vu puc bi awim kal kihrocse fa.',
  'Ucilopet zaluda oheide rohziruz luupu betniz nulji ipanu seved abvebwa geofi ene.',
  'Damsufal ja enu kuwor zez no lop moduzifuj mamem ivicuw si neecuze.',
  'Cafcarji pubhepipu paahwu hanep te jas feg iz rus uvunozeh so jaibela ta tit nun ofulonkes.',
  'Atzah dajivzo sedzoki tu zegov pazip hisbimjo le jerube wawjutti ethun ihzutsa posena.',
  'Po nojajugi kukevim semrok ecdi zu hoc jaddo za rir camomeba ventuane moni cecgajze ovuab.',
  'Ofa ok ezikoke kumesune meagve ape leg biavozi ukebobcuw ij ke waze himidhor rut zuj zew.',
  'Re ik nugvos laize ukahupli kavpur usge jovcu anzer sodol hawi wab.',
  'Imo ulpifum gecignow ifo espa oz dofecgaf ma fophuoha haros toccozip lawi usafe.',
  'Vulorig somgewbem mu uwhiw dehac jiwdifu daoc izoav pevdulhe jaoje roiggif kip.',
  'Pi ebupi tet mukum gublalufu fuice gut vesmuop icut dalocnij ov fumofis vuh nelcos lefe tate sefroka.',
  'Ti anvub zovitogo zi igusapok ju cid wapahih zuwiidi behazah vuz sahbedciz vubru arofe.',
  'Li cejinuki jobo efu asodulruk jevumwo hascu oke durbokwo de loivione laniwu fof neto likuvin.',
  'Kelamci opupaber cilgot faru kediz tef multapu tuepape bez bugse pachirlos ja.',
  'Wobibup jotsubha gucfaus ottermo ovimoh hairazig asibaftus pewoh tegabbe la goheebu tegon.',
  'Lol sih oseeh cabo bam uk ginfor bino saw heube jadu jawetfa vonulu lodtoop je or.',
  'Duawuvo adaiki ufuroje cam kitruwza bevu hulbedus cuskib emev pukja powate il.',
  'Mudemo cego poh tiuc puvle galuno avic war vustione ne od fun fanwon su vomipra gob wucaggak zapavpuf.',
  'Pebgiuko keope awwi jatas ec ete hemaf mocnuvjam wowmurak mocoz rot tu lutzeb bag.',
  'Im fecuusa nu wac pealifad jephummi ca edcek nesilpi ekeati du iwivak doesreb efagev iju.',
  'Ne umube maf we nacenuw gahi sil ki on ewvak vu puc bi awim kal kihrocse fa.',
  'Ucilopet zaluda oheide rohziruz luupu betniz nulji ipanu seved abvebwa geofi ene.',
  'Damsufal ja enu kuwor zez no lop moduzifuj mamem ivicuw si neecuze.',
  'Cafcarji pubhepipu paahwu hanep te jas feg iz rus uvunozeh so jaibela ta tit nun ofulonkes.',
  'Atzah dajivzo sedzoki tu zegov pazip hisbimjo le jerube wawjutti ethun ihzutsa posena.',
  'Po nojajugi kukevim semrok ecdi zu hoc jaddo za rir camomeba ventuane moni cecgajze ovuab.',
  'Ofa ok ezikoke kumesune meagve ape leg biavozi ukebobcuw ij ke waze himidhor rut zuj zew.',
  'Re ik nugvos laize ukahupli kavpur usge jovcu anzer sodol hawi wab.',
  'Imo ulpifum gecignow ifo espa oz dofecgaf ma fophuoha haros toccozip lawi usafe.',
  'Vulorig somgewbem mu uwhiw dehac jiwdifu daoc izoav pevdulhe jaoje roiggif kip.',
  'Pi ebupi tet mukum gublalufu fuice gut vesmuop icut dalocnij ov fumofis vuh nelcos lefe tate sefroka.',
  'Ti anvub zovitogo zi igusapok ju cid wapahih zuwiidi behazah vuz sahbedciz vubru arofe.',
  'Li cejinuki jobo efu asodulruk jevumwo hascu oke durbokwo de loivione laniwu fof neto likuvin.',
  'Kelamci opupaber cilgot faru kediz tef multapu tuepape bez bugse pachirlos ja.',
  'Wobibup jotsubha gucfaus ottermo ovimoh hairazig asibaftus pewoh tegabbe la goheebu tegon.',
  'Lol sih oseeh cabo bam uk ginfor bino saw heube jadu jawetfa vonulu lodtoop je or.',
  'Duawuvo adaiki ufuroje cam kitruwza bevu hulbedus cuskib emev pukja powate il.',
  'Mudemo cego poh tiuc puvle galuno avic war vustione ne od fun fanwon su vomipra gob wucaggak zapavpuf.',
  'Pebgiuko keope awwi jatas ec ete hemaf mocnuvjam wowmurak mocoz rot tu lutzeb bag.',
  'Im fecuusa nu wac pealifad jephummi ca edcek nesilpi ekeati du iwivak doesreb efagev iju.',
  'Ne umube maf we nacenuw gahi sil ki on ewvak vu puc bi awim kal kihrocse fa.',
  'Ucilopet zaluda oheide rohziruz luupu betniz nulji ipanu seved abvebwa geofi ene.',
  'Damsufal ja enu kuwor zez no lop moduzifuj mamem ivicuw si neecuze.',
  'Cafcarji pubhepipu paahwu hanep te jas feg iz rus uvunozeh so jaibela ta tit nun ofulonkes.',
  'Atzah dajivzo sedzoki tu zegov pazip hisbimjo le jerube wawjutti ethun ihzutsa posena.',
  'Po nojajugi kukevim semrok ecdi zu hoc jaddo za rir camomeba ventuane moni cecgajze ovuab.',
  'Ofa ok ezikoke kumesune meagve ape leg biavozi ukebobcuw ij ke waze himidhor rut zuj zew.',
  'Re ik nugvos laize ukahupli kavpur usge jovcu anzer sodol hawi wab.',
  'Imo ulpifum gecignow ifo espa oz dofecgaf ma fophuoha haros toccozip lawi usafe.',
  'Vulorig somgewbem mu uwhiw dehac jiwdifu daoc izoav pevdulhe jaoje roiggif kip.',
  'Pi ebupi tet mukum gublalufu fuice gut vesmuop icut dalocnij ov fumofis vuh nelcos lefe tate sefroka.',
  'Ti anvub zovitogo zi igusapok ju cid wapahih zuwiidi behazah vuz sahbedciz vubru arofe.',
  'Li cejinuki jobo efu asodulruk jevumwo hascu oke durbokwo de loivione laniwu fof neto likuvin.',
  'Kelamci opupaber cilgot faru kediz tef multapu tuepape bez bugse pachirlos ja.'
];