// import Chance from 'chance';
//
// const chance = new Chance();
//
// const result = new Array(2).fill(1).map(() => chance.sentence());
//
// export default result;


export default [ 'First - Fav sumozo raf anenu lo edra omumo sizevpup sulemal ta tefa gohjanor.',
  'Ho pi pulsoze kipot don rohesaem mem kaz uh lirjer ovaopoluz ci ibe ubi binena sidzabil de.',
  'Ewafro higeko ececo nirnejal sif ta zon bas tose fij jer node hahcobum.',
  'Solo bezurwo idibolip bep of fobba delgud ned few babagivo kiz sec ho roju.',
  'Cuhgiwkim tela kib mavafepe besev lomsadvij re ci tah wi sihisvo gu lu hojni.',
  'Ki nifu nit umifama dodeigi watko bimtuf jatu osole lekeh lighiziv riwobu zucew cuataca nugi jiwo.',
  'Wel uksawi apda iwe nel narri irbap ranlemubu gik ag ordimi pidcitiv zogpu lajemla.',
  'Kumoccaf tozuhaj af lolha nu kovna polopiha difa fehim vorsugru fi zeccajom uporuw bikkilet zas nejavsec.',
  'Vil didees ubo sudnero mim tubiva ha us beribub vestu nahpowno of seb.',
  'Ufoviovo wawolnoz si sedhu nen direjivor femnu eja itius emohupin uctem lovug voajuahe.',
  'Peklujah mukibe nahsisme va sam siglugud nah pu da bonamalo lof so jutrin subverbuj soalini agiuwa ci.',
  'Obu haculfej mes cozsuana gorwiwvig kujbu cohisgi icopiiwe nopud va ca replo za lufpos renop kub hah devoroz.',
  'Keluwfig af ziw ac tekcif dorpet wavivet lek luz efi temojed mo mu ej.',
  'Pi sok bidsad tim sawedo ze tobe voekion fibu kougahef deazail ruf hud na awiajtam naijauz.',
  'Beducak do kezim vuezaik jufoc zif si hinzuc befzip fuwetin ni zivireec fej ninobfar cogirpob pog.',
  'Ole viife kuipto hoh jumibub apota dofce fe litcop pelheral nob enidasho kus wonco sazze feobu rucevda war.',
  'Sin ve tiwijluv mozmebe da ub hup cegod jocag la utci juhiv avesona su ezaulocic bavuf.',
  'Ar bej zuj iguzu mu kawac rasohze ca baapubag upakufvit zase rak piz muj.',
  'Ozi coco pogbilki ofahe tokvo hu avmece gumece buk eliefu boflolu aco.',
  'Wuazvi ake lakwow kewugwe vij kogiz sutompan jebaktim ot vuj tuv visimfi ju jiw.',
  'Mub levif obto kajmi kah voh kalgamtum sucfulfo giut roipu edioma ba.',
  'Ida gepof mitgurrep uvocuvpeg not im cekroblat lap uru muces cez afi elpaspar wemweji bavaski ehjiz gurmazawo tekkoku.',
  'Mu at liwaas duj suod caijzah dodik is zuzar het lamrus na.',
  'Sehucut ci ifpiv takrabu lo paefel uriroopu muvul zujin ow ul wow.',
  'Fo azzim ninje efelatbem vuot duzo buwotja tatuwabi puc anvohfug ilju vijwuh ko.',
  'Olba wap pidgawen nonlar serusu pok lo bikealu akoica zo los ruijwos pujawaf.',
  'Sigrig eb wa ema as ud ozopeiw udiodi vu gakzus ifnornuf de vojus nigkucse bara reljujiwo.',
  'Pavuzen evwimab mug afajobli cedgufe nases dakkemse bavi roguga iw jepgauha so sugte.',
  'Til rub ro ezurupe saz ka fuha emigu ec forofob kien papzo riah ekawa iwfu fugecga zilcot.',
  'Kufbojne gejdakbi itvi ocfel pu koturfaw ornazgig woigo kun jaoruefi mif genor hefe eg josju apo.',
  'Nironilas divuz bu belaphin gilpivuj tufe fi gavasowul kirab po dawidime vawta wi cepec lidse.',
  'Le erobipha pewitsam didler dunebe ohcutig iwo kekaj icnunnev ucalet ra jifec cev zohagaj mezgiw jel awlu.',
  'Risweus wel hikotana afiwadik iki tul jukomip sukbi lup ilgo cu ot aletu miapo wu ham wuche.',
  'Fanbavig na aceudiza hid avluj buz inacusi ne cunepaki fazajno bawig rowavha.',
  'Firuh su hav saviwri hi zavvijo zisu tudgac juvojuos igejukupe aw ase ze falfe uja.',
  'Ulluf od lub zeghof zidimikec veb dothalfon puvov eb bacsuzu lu ejoosjez tipem ipongen ponug.',
  'Ke luri ipfij mupci jewih ginegmag mu roh wafuszo jodir bum el sibkusi noiwu jutad huroge zulmi.',
  'Zu rib hocadne uckugje ruwef ojwav riv sip sud beafe kasi zamitida amhici lod rizimas ric ocatu ted.',
  'Ejifa ci faf limup pef dorrona oba re pe emcun du astaca ravozer.',
  'Hitrehwi tozloves hebmu curho umo dani la wujlota baz cazlaw jo jomcub pe dem cepwec kaigo demiznat relhafej.',
  'Im zucuazo kukve ubju ucluvsut lur uso noibbi du wonavpum nohhimew radzu mobnojme rog.',
  'Nah nawevor disoz uvmagra joto ajolatjo atetoum be linvet imitu widirgeb fecep puk cerzo fivofer.',
  'Deevala raced duozo cevom vaz bu meh zav punuvuzo uhovozkuh rajsuh cugob vop teosbav jo.',
  'Du bo ezu jipujed ulbel ravnessuv lodup lu husiw tisonimor bijun ejju su lesehol umikef tidsut nelapu.',
  'Mefwe rirza kofol ticvedek garhaf ite gada virhozah budla tatavi ek got.',
  'Ti sa uk cenlu tos wikemal wuphovzeg efu vorwu pucebsu hercan jal.',
  'Ji wag titeij tufvanute hanvuh moh gevuk woffur rugof giife ce to.',
  'Espezose fusaw sek ka ata umbiz gosu pedonho oz iknov wetik soosa.',
  'Luwco dehom hurinen miji jedez un lajugofi fena ab devow dusih wu sef romgoj.',
  'Ge donije kojro izokan losas bivsiz reej vaim vohi ez unumu fevgiv fov sovum cudami pudawig.',
  'Nupberoj pa jim unuifcep ba kub to wefev wobek jeg cavuew bacam abihoked tipse line edik lacijbo.',
  'Kuj seaf meiz dab bo puodfun kenti pizcavfit wis wu ju ba figit.',
  'Keho uvifal olfohet obajjo anzobuk fibek rehac ja baceb wo ivovelba tommu goer.',
  'Kibeis imesuba dosga mig kinsiw bu detisnim kide nalfodif cu cukizjem coage inwuori soj bu.',
  'Bemi banpefa paraz bek te loncoiga ekjuzhir hedecehe ereta cebetaojo ena asinirof iponorraz.',
  'Dusse cewa lubmig govab zosren te noc cupzesiz uma bivocle me pi hes lassan vure.',
  'Capfuteh sossivim meagkaz wohwikeh uf vuba re hin lar moma udonamat luc avverpew hiovgep ra jegdatik feci.',
  'Ufubeduw lidofmoc kideb limpumob capinluc odef tufoco cow imuso jo ke odutuzwo das dojri unimeag hiz kaco kavlel.',
  'Goleg zasivik wozo te guvo ve utsamgo beezerep von fi er he liti eloberfi.',
  'Ka fenusjew le livinne ehijafa aki jureve fuctov za veh vozjorru darlu fo.',
  'Owanin kov cawof pem riula fun pespipif do caw wejfaem ov ho tuk lomze irase nem.',
  'Caewdar jiuc vavo cos ja purupod bermim na kizop tito mef zaloli.',
  'Ijeal co ecoide hewrifi ic ehtur na gaw vedgonat nati ibfolo dagiha zulan goncenah ja.',
  'Wosukeli sihzos uni humfok af hi hi gahla fu cu inbephu poitemij bavje odzorar iknagwe tun aneviku rib.',
  'Jip biw ulatoce wu icru udano odagu ozohovsat duv ne lop lemhu jasob igovog gosoh fit viwnujile emuawveb.',
  'Anjuzku pi decbifhe dij zuc howed taj coni johba muewi vowja buvav.',
  'Bu mevnih su jejuj pag ola to al tenpuric cupa paudika vurulan uve gezobebu.',
  'Voijsar pe soc un zoj ma boecodud sodci piefa giw tun jokevele jezvuowi tetowcu mot so povka.',
  'Nivheih milofmar kovkalul zuhmos bezu niurean avojas ufoji behmak taadego sovojoh awo mabobza pi.',
  'Noiwiecu dizip da ahogeselo ugtaben wamacos nafned jip obetmu oh winew et ojmu dov uw.',
  'Jongip kahiron ra ohonegpi piwob uw vevunfaz zeudi siom ohujahid jamfi totijguf.',
  'Ve ame ta su damselco fihlune bigibo onaus ek nujofna cadofned ku johi jum.',
  'Re zosbefmo pavupif ku awi kuchemom al enunuzuv dotag de bew rivsebbar demlug ivueme hisig gajuz.',
  'Rufi necvup ernagce gu dij idepom zulo laiticum te ekaot pewbe lev ceb mudcaeku kalbu.',
  'Wujgawep pasak fah misce iw golbora viot av mieti ofa cocodnom lu debomvi.',
  'On ri rum edmo calov kerowuv fobe zinfu fovneva ret paudifa juja pom opga vezleha.',
  'Vu noami johozzur izi pofzo re tenili saiw ve duasune kinpihcoh sarpe.',
  'Mu re beb fono sobturmes vih hu ufodetcu sice jopih zardic ekwos.',
  'Buw witze poga fujvid hanalbem algeahu lespathod itogoh obkat mor pidagju roho.',
  'Ojudoja utafosre vungitud kiwos gaojo iculijaj vipeesi wuwam ze dubokir me fu.',
  'Obohu zo gocub ziaj usi geibu cezgedjo mo horemce ub apehu vigfimo ab loefadac lihima eh pun.',
  'Rewram popfoz gok jetveuf torenod hev fe zidzi reg wunacrus datfuhod are rojicat pocaf lekup hudlas ma sacuhgi.',
  'Ceffelnu se hacwecca akouzuda joblola cugi hifu husudiuj eripomam venowil pab gadsahi aje retjewtuk acew wivahliz leudma.',
  'Zemudu ice kujvudef corbuca dehiki ahe kada cabdene runraf en reke leb.',
  'Ko hati abefoh fujjep bimigpu herbanaho hes tanuvlo va dunzulo legok rivibgen.',
  'Fe ofa pukrara ranacal sukotket va boidmi led dekodmah ce ifwabfe sicehu vofito kovo ip dovuc.',
  'Cen zu buc fugur junra tuwzeos zapfi gedoere ri rivoade mipzu sot amew jetkew zicwa bodhiom puj vewu.',
  'Azbi koeboko pog piipzi li cubuceov bilos itamohhog ziufa olerofvo bavce ogobatlon kikol.',
  'De mobpiga ajobasduh ivelo kuradfu hacce hut usu leidori nofo os pokrur eto mujivik.',
  'Ugzed iwcaol wefiguse wawe rut kima uve tevof addub havte orujep dupagsud nir kijre ke lonzem.',
  'Urtij paihenef ha muigoug iga paz hi pizotu pasafov ovufi egakavo tiwhehzuk keleg caupo.',
  'Omoov numakhov ne fof had pojuw iwjiif cotje gum melzo pus jake zacuhuguf geger.',
  'Rumu nasin duozu do kiv tipihpo jaen jivnamso ok zukog as sefebpit der roes ow zog.',
  'Penus motivude le dah fof savpuavi gok dak nitoh duzo vew rahibahi besfi vuwheem of.',
  'Bomfi zahjojser luhisicul biv amavu pophu ahoge ibaba neroko si keg jan otju elufijuzi zu zu timsuki.',
  'Ceglojen jakiv va muffap goszibzo kulelu semugnuz zevebo ojneup zah jeslim otujaju ripidu dudjir hijki je.',
  'Ce bievci balihip duic heh ewjif malilzi ziw ir ate sakjo vuwrouj cekpejpa ovvajez ceavitiz acuvevjo rev zuwa.',
  'Navvaeb amarop lome fadjanisu kasfuk duciw fuzis jigewipa goljef jerdu la cat.',
  'Riw ek guge witpa zehos ra raedu hevihbo nag zi geruob bujkof ros bofaf zepdo wi.',
  'Most Recent - Fekagse kotwo ceewa gen koc na gebigi tarbefne picwisesi wubag rafo hektil penik di.'
];
